site_name: pyrung
site_description: Documentation for pyrung
repo_url: https://github.com/ssweber/pyrung

theme:
  name: material

nav:
  - Home: index.md
  - API Reference:
      - Overview: reference/index.md

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_reference.py
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            filters:
              - "!^_"
            heading_level: 2
            inherited_members: false
            members_order: source
            separate_signature: true
            show_root_heading: true
            show_root_toc_entry: false
            show_signature_annotations: true
            show_source: false

exclude_docs: |
  click_reference/**

not_in_nav: |
  reference/api/**

markdown_extensions:
  - admonition
  - attr_list
